### ISSUE TITLE
is it possible to run mac M2 ultra?

### ISSUE THREAD

**Issue by bioinfomagic** [microsoft/LLaVA-Med#11]
I don't have a nvdia device and wish to learn how to run LLaVA-med, wondering if is it possible to run mac M2 ultra 198 GB?
Previous LLaVA runs on Mac M2 chip slowly, which is working on mac, not sure if LLaVA-med also supports Mac.

**Comment by bioinfomagic** [comment]
Downloading open_clip_torch-2.23.0-py3-none-any.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 4.3 MB/s eta 0:00:00
Installing collected packages: ftfy, open-clip-torch
Successfully installed ftfy-6.1.1 open-clip-torch-2.23.0
Collecting flash-attn
  Using cached flash_attn-2.3.3.tar.gz (2.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      /private/var/folders/r1/_sncvgk15lb_fhsrrjjhj_wh0000gn/T/pip-install-dbtvbswe/flash-attn_49645c10a8284b98b548df3b1535e0fb/setup.py:79: UserWarning: flash_attn was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/r1/_sncvgk15lb_fhsrrjjhj_wh0000gn/T/pip-install-dbtvbswe/flash-attn_49645c10a8284b98b548df3b1535e0fb/setup.py", line 136, in <module>
          CUDAExtension(
        File "/opt/homebrew/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1076, in CUDAExtension
          library_dirs += library_paths(cuda=True)
                          ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1203, in library_paths
          if (not os.path.exists(_join_cuda_home(lib_dir)) and
                                 ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2416, in _join_cuda_home
          raise OSError('CUDA_HOME environment variable is not set. '
      OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
      
      
      torch.__version__  = 2.1.0
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
