### ISSUE TITLE
Released files: 404 error

### ISSUE THREAD

**Issue by SinanAkkoyun** [microsoft/LLaVA-Med#13]
Thank you so so much for releasing all the data and models!

I get the following error:
```
Downloading PMC articles
  0%|                                                                                            | 916/721154 [33:49<443:15:00,  2.22s/it]
Traceback (most recent call last):
  File "llava/data/download_images.py", line 43, in <module>
    main(args)
  File "llava/data/download_images.py", line 19, in main
    urllib.request.urlretrieve(sample['pmc_tar_url'], os.path.join(args.pmc_output_path, os.path.basename(sample['pmc_tar_url'])))
  File "/usr/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by SinanAkkoyun** [comment]
And also, this is the LlaVa Med 2 release, right?

**Comment by SinanAkkoyun** [comment]
> No, this is the original LLaVA-Med release, after going through 5-month intensive discussions to comply with Microsoft release policy.

@ChunyuanLI I see, thank you so so much for going through the trouble!

**Comment by Kingofolk** [comment]
Hi, have you solved this problem? I encountered a similar problem. When using download_images.py to download PMC articals, the downloading process stopped at 916/721145 unexpectedly. To be more clearly, please see the following snapshot.
![image](https://github.com/microsoft/LLaVA-Med/assets/37804732/e6c82f38-4e74-44cd-8bcb-f06fd434a6c4)
Looking forward for your reply. Thanks a lot.
