### ISSUE TITLE
NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE.

### ISSUE THREAD

**Issue by HaotianHuang** [microsoft/LLaVA-Med#17]
Hi there, trying to inference using gradio client but running into difficulty reported as `"NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE."` when using sample image and text input (see below). 

Primary traceback error is `2023-11-15 04:02:56 | ERROR | stderr |     images = images.to(self.model.device, dtype=torch.float16).`

What I've tried
- Changing timeout=10 to timeout=5000 in gradio_web_server.py in output stream as per [this thread](https://github.com/lm-sys/FastChat/issues/1206)

Haven't tried
- Upgrading to A100

What I believe the problem is
- Error shifting image to GPU for inference. 

<img width="1339" alt="Screen Shot 2023-11-15 at 2 52 40 pm" src="https://github.com/microsoft/LLaVA-Med/assets/34679147/101ff876-124e-4e80-9262-5f19f215fff6">

Test message seems to work
```
/colab# python -m llava.serve.test_message --model-name LLaVA-Med-7B --controller http://localhost:10000
2023-11-15 03:57:18.355083: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-15 03:57:18.355167: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-15 03:57:18.355196: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-15 03:57:19.667608: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Models: ['LLaVA-Med-7B']
worker_addr: http://localhost:40000
A chat between a curious human and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the human's questions.
Human: What are the key differences between renewable and non-renewable energy sources?
Assistant: Renewable energy sources are those that can be replenished naturally in a relatively short amount of time, such as solar, wind, hydro, geothermal, and biomass. Non-renewable energy sources, on the other hand, are finite and will eventually be depleted, such as coal, oil, and natural gas. Here are some key differences between renewable and non-renewable energy sources:
1. Availability: Renewable energy sources are virtually inexhaustible, while non-renewable energy sources are finite and will eventually run out.
2. Environmental impact: Renewable energy sources have a much lower environmental impact than non-renewable sources, which can lead to air and water pollution, greenhouse gas emissions, and other negative effects.
3. Cost: Renewable energy sources can be more expensive to initially set up, but they typically have lower operational costs than non-renewable sources.
4. Reliability: Renewable energy sources are often more reliable and can be used in more remote locations than non-renewable sources.
5. Flexibility: Renewable energy sources are often more flexible and can be adapted to different situations and needs, while non-renewable sources are more rigid and inflexible.
6. Sustainability: Renewable energy sources are more sustainable over the long term, while non-renewable sources are not, and their depletion can lead to economic and social instability.

Human: Hello do you understand images?.
 Assistant: Hello, the computer recognizes images with a resolution of 720p or higher.
 Assistant: Hello, the computer recognizes images with a resolution of 720p or higher.
```

Gradio web server seems okay
```
/colab# python -m llava.serve.gradio_web_server --controller http://localhost:10000
2023-11-15 03:59:04.100293: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-15 03:59:04.100352: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-15 03:59:04.100381: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-15 03:59:05.497943: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-11-15 03:59:09 | INFO | gradio_web_server | args: Namespace(host='0.0.0.0', port=None, controller_url='http://localhost:10000', concurrency_count=8, model_list_mode='once', share=True, moderate=False, embed=False)
2023-11-15 03:59:09 | INFO | gradio_web_server | Models: ['LLaVA-Med-7B']
2023-11-15 03:59:09 | INFO | gradio_web_server | Namespace(host='0.0.0.0', port=None, controller_url='http://localhost:10000', concurrency_count=8, model_list_mode='once', share=True, moderate=False, embed=False)
2023-11-15 03:59:10 | INFO | stdout | Running on local URL:  http://0.0.0.0:7860
2023-11-15 03:59:11 | INFO | stdout | Running on public URL: https://ffc0c282c186ffb9f9.gradio.live
2023-11-15 03:59:11 | INFO | stdout | 
2023-11-15 03:59:11 | INFO | stdout | This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
2023-11-15 03:59:27 | INFO | gradio_web_server | load_demo. ip: 172.31.29.141. params: {}
2023-11-15 03:59:27 | INFO | httpx | HTTP Request: POST http://localhost:7860/api/predict "HTTP/1.1 200 OK"
2023-11-15 03:59:27 | INFO | httpx | HTTP Request: POST http://localhost:7860/reset "HTTP/1.1 200 OK"
2023-11-15 03:59:35 | INFO | gradio_web_server | add_text. ip: 172.31.29.141. len: 25
2023-11-15 03:59:35 | INFO | httpx | HTTP Request: POST http://localhost:7860/api/predict "HTTP/1.1 200 OK"
2023-11-15 03:59:35 | INFO | httpx | HTTP Request: POST http://localhost:7860/reset "HTTP/1.1 200 OK"
2023-11-15 03:59:37 | INFO | gradio_web_server | http_bot. ip: 172.31.29.141
2023-11-15 03:59:37 | INFO | gradio_web_server | model_name: LLaVA-Med-7B, worker_addr: http://localhost:40000
2023-11-15 03:59:37 | INFO | gradio_web_server | ==== request ====
{'model': 'LLaVA-Med-7B', 'prompt': 'You are LLaVA-Med, a large language and vision assistant trained by a group of researchers at Microsoft, based on the general domain LLaVA architecture.You are able to understand the visual content that the user provides, and assist the user with a variety of medical and clinical tasks using natural language.Follow the instructions carefully and explain your answers in detail.###Human: Hi!###Assistant: Hi there!  How can I help you today?\n###Human: What is this image about?\n<image>###Assistant:', 'temperature': 0.2, 'max_new_tokens': 512, 'stop': '###', 'images': "List of 1 images: ['c98a0941c1b4e20feb7ac190b92615ba']"}
2023-11-15 03:59:37 | INFO | httpx | HTTP Request: POST http://localhost:7860/api/predict "HTTP/1.1 200 OK"
2023-11-15 03:59:37 | INFO | httpx | HTTP Request: POST http://localhost:7860/api/predict "HTTP/1.1 200 OK"
2023-11-15 03:59:37 | INFO | httpx | HTTP Request: POST http://localhost:7860/api/predict "HTTP/1.1 200 OK"
2023-11-15 03:59:38 | INFO | httpx | HTTP Request: POST http://localhost:7860/reset "HTTP/1.1 200 OK"
```

Controller seems alright
```
/colab/LLaVA-Med# python -m llava.serve.controller --host 0.0.0.0 --port 10000
2023-11-15 04:02:27.783156: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-15 04:02:27.783211: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-15 04:02:27.783237: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-15 04:02:29.148015: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-11-15 04:02:31 | INFO | controller | args: Namespace(host='0.0.0.0', port=10000, dispatch_method='shortest_queue')
2023-11-15 04:02:31 | INFO | controller | Init controller
2023-11-15 04:02:31 | ERROR | stderr | INFO:     Started server process [61479]
2023-11-15 04:02:31 | ERROR | stderr | INFO:     Waiting for application startup.
2023-11-15 04:02:31 | ERROR | stderr | INFO:     Application startup complete.
2023-11-15 04:02:31 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:10000 (Press CTRL+C to quit)
2023-11-15 04:02:35 | INFO | controller | Receive unknown heart beat. http://localhost:40000
2023-11-15 04:02:35 | INFO | stdout | INFO:     127.0.0.1:59348 - "POST /receive_heart_beat HTTP/1.1" 200 OK
2023-11-15 04:02:35 | INFO | controller | Register a new worker: http://localhost:40000
2023-11-15 04:02:35 | INFO | controller | Register done: http://localhost:40000, {'model_names': ['LLaVA-Med-7B'], 'speed': 1, 'queue_length': 1}
2023-11-15 04:02:35 | INFO | stdout | INFO:     127.0.0.1:59350 - "POST /register_worker HTTP/1.1" 200 OK
2023-11-15 04:02:50 | INFO | controller | Receive heart beat. http://localhost:40000
2023-11-15 04:02:50 | INFO | stdout | INFO:     127.0.0.1:57184 - "POST /receive_heart_beat HTTP/1.1" 200 OK
2023-11-15 04:02:56 | INFO | controller | names: ['http://localhost:40000'], queue_lens: [1.0], ret: http://localhost:40000
2023-11-15 04:02:56 | INFO | stdout | INFO:     127.0.0.1:57186 - "POST /get_worker_address HTTP/1.1" 200 OK
2023-11-15 04:02:56 | INFO | controller | Receive heart beat. http://localhost:40000
2023-11-15 04:02:56 | INFO | stdout | INFO:     127.0.0.1:57192 - "POST /receive_heart_beat HTTP/1.1" 200 OK
2023-11-15 04:03:05 | INFO | controller | Receive heart beat. http://localhost:40000
2023-11-15 04:03:05 | INFO | stdout | INFO:     127.0.0.1:44164 - "POST /receive_heart_beat HTTP/1.1" 200 OK
2023-11-15 04:03:20 | INFO | controller | Receive heart beat. http://localhost:40000
2023-11-15 04:03:20 | INFO | stdout | INFO:     127.0.0.1:49366 - "POST /receive_heart_beat HTTP/1.1" 200 OK
```

Worker has trouble
```
2023-11-15 04:02:35 | INFO | model_worker | Register to controller
2023-11-15 04:02:50 | INFO | model_worker | Send heart beat. Models: ['LLaVA-Med-7B']. Semaphore: Semaphore(value=4, locked=False). global_counter: 2
2023-11-15 04:02:56 | INFO | model_worker | Send heart beat. Models: ['LLaVA-Med-7B']. Semaphore: Semaphore(value=3, locked=False). global_counter: 3
2023-11-15 04:02:56 | INFO | stdout | INFO:     127.0.0.1:45762 - "POST /worker_generate_stream HTTP/1.1" 200 OK
2023-11-15 04:02:56 | ERROR | stderr | ERROR:    Exception in ASGI application
2023-11-15 04:02:56 | ERROR | stderr | Traceback (most recent call last):
2023-11-15 04:02:56 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
2023-11-15 04:02:56 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2023-11-15 04:02:56 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2023-11-15 04:02:56 | ERROR | stderr |     return await self.app(scope, receive, send)
2023-11-15 04:02:56 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1106, in __call__
2023-11-15 04:02:56 | ERROR | stderr |     await super().__call__(scope, receive, send)
2023-11-15 04:02:56 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 122, in __call__
2023-11-15 04:02:56 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2023-11-15 04:02:56 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
2023-11-15 04:02:56 | ERROR | stderr |     raise exc
2023-11-15 04:02:56 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
2023-11-15 04:02:56 | ERROR | stderr |     await self.app(scope, receive, _send)
2023-11-15 04:02:56 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
2023-11-15 04:02:56 | ERROR | stderr |     raise exc
2023-11-15 04:02:56 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-11-15 04:02:56 | ERROR | stderr |     await self.app(scope, receive, sender)
2023-11-15 04:02:56 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
2023-11-15 04:02:56 | ERROR | stderr |     raise e
2023-11-15 04:02:56 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
2023-11-15 04:02:56 | ERROR | stderr |     await self.app(scope, receive, send)
2023-11-15 04:02:56 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 718, in __call__
2023-11-15 04:02:56 | ERROR | stderr |     await route.handle(scope, receive, send)
2023-11-15 04:02:56 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
2023-11-15 04:02:56 | ERROR | stderr |     await self.app(scope, receive, send)
2023-11-15 04:02:56 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 69, in app
2023-11-15 04:02:56 | ERROR | stderr |     await response(scope, receive, send)
2023-11-15 04:02:56 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 270, in __call__
2023-11-15 04:02:56 | ERROR | stderr |     async with anyio.create_task_group() as task_group:
2023-11-15 04:02:56 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
2023-11-15 04:02:56 | ERROR | stderr |     raise exceptions[0]
2023-11-15 04:02:56 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 273, in wrap
2023-11-15 04:02:56 | ERROR | stderr |     await func()
2023-11-15 04:02:56 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 262, in stream_response
2023-11-15 04:02:56 | ERROR | stderr |     async for chunk in self.body_iterator:
2023-11-15 04:02:56 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/concurrency.py", line 63, in iterate_in_threadpool
2023-11-15 04:02:56 | ERROR | stderr |     yield await anyio.to_thread.run_sync(_next, iterator)
2023-11-15 04:02:56 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
2023-11-15 04:02:56 | ERROR | stderr |     return await get_asynclib().run_sync_in_worker_thread(
2023-11-15 04:02:56 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
2023-11-15 04:02:56 | ERROR | stderr |     return await future
2023-11-15 04:02:56 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
2023-11-15 04:02:56 | ERROR | stderr |     result = context.run(func, *args)
2023-11-15 04:02:56 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/concurrency.py", line 53, in _next
2023-11-15 04:02:56 | ERROR | stderr |     return next(iterator)
2023-11-15 04:02:56 | ERROR | stderr |   File "/content/drive/MyDrive/colab/LLaVA-Med/llava/serve/model_worker.py", line 296, in generate_stream_gate
2023-11-15 04:02:56 | ERROR | stderr |     for x in self.generate_stream(params):
2023-11-15 04:02:56 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 35, in generator_context
2023-11-15 04:02:56 | ERROR | stderr |     response = gen.send(None)
2023-11-15 04:02:56 | ERROR | stderr |   File "/content/drive/MyDrive/colab/LLaVA-Med/llava/serve/model_worker.py", line 216, in generate_stream
2023-11-15 04:02:56 | ERROR | stderr |     images = images.to(self.model.device, dtype=torch.float16)
2023-11-15 04:02:56 | ERROR | stderr | RuntimeError: CUDA error: device-side assert triggered
2023-11-15 04:02:56 | ERROR | stderr | Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
2023-11-15 04:02:56 | ERROR | stderr | 
2023-11-15 04:03:05 | INFO | model_worker | Send heart beat. Models: ['LLaVA-Med-7B']. Semaphore: Semaphore(value=3, locked=False). global_counter: 3
2023-11-15 04:03:20 | INFO | model_worker | Send heart beat. Models: ['LLaVA-Med-7B']. Semaphore: Semaphore(value=3, locked=False). global_counter: 3
2023-11-15 04:03:35 | INFO | model_worker | Send heart beat. Models: ['LLaVA-Med-7B']. Semaphore: Semaphore(value=3, locked=False). global_counter: 3
2023-11-15 04:03:50 | INFO | model_worker | Send heart beat. Models: ['LLaVA-Med-7B']. Semaphore: Semaphore(value=3, locked=False). global_counter: 3
```

Specifications
- Running on Google Colab V100 High Ram
- System RAM: 51.0 GB
- GPU RAM: 16.0 GB
- Image below is from a few consecutive inference tests

<img width="399" alt="image" src="https://github.com/microsoft/LLaVA-Med/assets/34679147/e15e6588-e44b-4308-9ed2-d011f353d2eb">

**Comment by atultiwari** [comment]
Hi,
did you find a solution to this problem.
I also want to test this repo, but I am stuck at very beginning steps. I have posted my issue [here](https://github.com/microsoft/LLaVA-Med/issues/19)
can you please let me know how were you able to run it this far?
if you can share your colab notebook, that would be a great help.
Thank you
Regards,
Dr. Atul

**Comment by yihp** [comment]
@HaotianHuang Hello, I also encountered the same problem, have you solved it?
