### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by atultiwari** [microsoft/LLaVA-Med#21]
Hi,
When I try to the Serving commands either launching a model worker, sending test message or launch gradio webserver, I always get `ConnectionRefused Error 111`. 
I have tried both on a rented A100 GPU via cloud service (jarvislabs.ai) and Google Colab Pro+.
I have tried following commands in both -

```
!python -m llava.serve.gradio_web_server --controller http://localhost:10000
!python -m llava.serve.test_message --model-name /content/drive/MyDrive/nlp/llava_med_model --controller http://localhost:10000
!python -m llava.serve.model_worker --host 0.0.0.0 --controller http://localhost:10000 --port 40000 --worker http://localhost:40000 --model-path /content/drive/MyDrive/nlp/llava_med_model --multi-modal
```

The complete error logs are -

```
2023-11-17 12:28:47.190995: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-17 12:28:47.191055: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-17 12:28:47.191120: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-17 12:28:48.382592: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f8a280a1a80>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=10000): Max retries exceeded with url: /refresh_all_workers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8a280a1a80>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/LLaVA-Med/llava/serve/test_message.py", line 62, in <module>
    main()
  File "/content/LLaVA-Med/llava/serve/test_message.py", line 14, in main
    ret = requests.post(controller_addr + "/refresh_all_workers")
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=10000): Max retries exceeded with url: /refresh_all_workers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8a280a1a80>: Failed to establish a new connection: [Errno 111] Connection refused'))

```

However when I try to launch a controller, it seems to work, however when I try to stop the execution of the code block, it still keeps on running. 
The command I execuated in Google Colab is -
`!python -m llava.serve.controller --host 0.0.0.0 --port 10000`

The complete log is -

```
2023-11-17 12:50:40.181860: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-17 12:50:40.181908: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-17 12:50:40.181976: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-17 12:50:41.422420: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-11-17 12:50:43 | INFO | controller | args: Namespace(host='0.0.0.0', port=10000, dispatch_method='shortest_queue')
2023-11-17 12:50:43 | INFO | controller | Init controller
2023-11-17 12:50:43 | ERROR | stderr | INFO:     Started server process [7142]
2023-11-17 12:50:43 | ERROR | stderr | INFO:     Waiting for application startup.
2023-11-17 12:50:43 | ERROR | stderr | INFO:     Application startup complete.
2023-11-17 12:50:43 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:10000/ (Press CTRL+C to quit)
2023-11-17 12:52:07 | ERROR | stderr | INFO:     Shutting down
2023-11-17 12:52:07 | ERROR | stderr | INFO:     Finished server process [7142]
2023-11-17 12:52:07 | ERROR | stderr | ERROR:    Traceback (most recent call last):
2023-11-17 12:52:07 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 686, in lifespan
2023-11-17 12:52:07 | ERROR | stderr |     await receive()
2023-11-17 12:52:07 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/lifespan/on.py", line 137, in receive
2023-11-17 12:52:07 | ERROR | stderr |     return await self.receive_queue.get()
2023-11-17 12:52:07 | ERROR | stderr |   File "/usr/lib/python3.10/asyncio/queues.py", line 159, in get
2023-11-17 12:52:07 | ERROR | stderr |     await getter
2023-11-17 12:52:07 | ERROR | stderr | asyncio.exceptions.CancelledError
2023-11-17 12:52:07 | ERROR | stderr |

```

I am unable to figure out the source of error. Any help would be great. It has been days, I wanted to test it out, but even after spending so much money on renting paid gpus and colab pro+ just for knowlege, but I am continuously hitting roadblock.

Thank you
Regards,
Atul

**Comment by Zoe-TAN** [comment]
Hi, I successfully ran the code with our dataset on Linux just following the instructions. It seems that the error you posted is related to the connection with the Colab rather than the code. I am not that familiar with the Colab (Sorry for that) so I suggest you run it locally.
