### ISSUE TITLE
NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE.

### ISSUE THREAD

**Issue by yihp** [microsoft/LLaVA-Med#41]
I did not get a normal response when running the example on the web page. The response was: "NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE."
![image](https://github.com/microsoft/LLaVA-Med/assets/130024120/b371bba4-ac72-465c-9bb2-5148ef638bdb)
The error message of the worker is as follows：
2024-01-17 02:28:33 | INFO | stdout | INFO:     127.0.0.1:33150 - "POST /worker_generate_stream HTTP/1.1" 200 OK
2024-01-17 02:28:33 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-01-17 02:28:33 | ERROR | stderr | Traceback (most recent call last):
2024-01-17 02:28:33 | ERROR | stderr |   File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 259, in __call__
2024-01-17 02:28:33 | ERROR | stderr |     await wrap(partial(self.listen_for_disconnect, receive))
2024-01-17 02:28:33 | ERROR | stderr |   File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 255, in wrap
2024-01-17 02:28:33 | ERROR | stderr |     await func()
2024-01-17 02:28:33 | ERROR | stderr |   File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 232, in listen_for_disconnect
2024-01-17 02:28:33 | ERROR | stderr |     message = await receive()
2024-01-17 02:28:33 | ERROR | stderr |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 538, in receive
2024-01-17 02:28:33 | ERROR | stderr |     await self.message_event.wait()
2024-01-17 02:28:33 | ERROR | stderr |   File "/usr/local/lib/python3.10/asyncio/locks.py", line 213, in wait
2024-01-17 02:28:33 | ERROR | stderr |     await fut
2024-01-17 02:28:33 | ERROR | stderr | asyncio.exceptions.CancelledError: Cancelled by cancel scope 7fbf95a23e50
2024-01-17 02:28:33 | ERROR | stderr | 
2024-01-17 02:28:33 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-01-17 02:28:33 | ERROR | stderr | 
2024-01-17 02:28:33 | ERROR | stderr |   + Exception Group Traceback (most recent call last):
2024-01-17 02:28:33 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
2024-01-17 02:28:33 | ERROR | stderr |   |     result = await app(  # type: ignore[func-returns-value]
2024-01-17 02:28:33 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2024-01-17 02:28:33 | ERROR | stderr |   |     return await self.app(scope, receive, send)
2024-01-17 02:28:33 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
2024-01-17 02:28:33 | ERROR | stderr |   |     await super().__call__(scope, receive, send)
2024-01-17 02:28:33 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 116, in __call__
2024-01-17 02:28:33 | ERROR | stderr |   |     await self.middleware_stack(scope, receive, send)
2024-01-17 02:28:33 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-01-17 02:28:33 | ERROR | stderr |   |     raise exc
2024-01-17 02:28:33 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-01-17 02:28:33 | ERROR | stderr |   |     await self.app(scope, receive, _send)
2024-01-17 02:28:33 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
2024-01-17 02:28:33 | ERROR | stderr |   |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-01-17 02:28:33 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 55, in wrapped_app
2024-01-17 02:28:33 | ERROR | stderr |   |     raise exc
2024-01-17 02:28:33 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
2024-01-17 02:28:33 | ERROR | stderr |   |     await app(scope, receive, sender)
2024-01-17 02:28:33 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 746, in __call__
2024-01-17 02:28:33 | ERROR | stderr |   |     await route.handle(scope, receive, send)
2024-01-17 02:28:33 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
2024-01-17 02:28:33 | ERROR | stderr |   |     await self.app(scope, receive, send)
2024-01-17 02:28:33 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
2024-01-17 02:28:33 | ERROR | stderr |   |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-01-17 02:28:33 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 55, in wrapped_app
2024-01-17 02:28:33 | ERROR | stderr |   |     raise exc
2024-01-17 02:28:33 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
2024-01-17 02:28:33 | ERROR | stderr |   |     await app(scope, receive, sender)
2024-01-17 02:28:33 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
2024-01-17 02:28:33 | ERROR | stderr |   |     await response(scope, receive, send)
2024-01-17 02:28:33 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 252, in __call__
2024-01-17 02:28:33 | ERROR | stderr |   |     async with anyio.create_task_group() as task_group:
2024-01-17 02:28:33 | ERROR | stderr |   |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
2024-01-17 02:28:33 | ERROR | stderr |   |     raise BaseExceptionGroup(
2024-01-17 02:28:33 | ERROR | stderr |   | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
2024-01-17 02:28:33 | ERROR | stderr |   +-+---------------- 1 ----------------
2024-01-17 02:28:33 | ERROR | stderr |     | Traceback (most recent call last):
2024-01-17 02:28:33 | ERROR | stderr |     |   File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 255, in wrap
2024-01-17 02:28:33 | ERROR | stderr |     |     await func()
2024-01-17 02:28:33 | ERROR | stderr |     |   File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 244, in stream_response
2024-01-17 02:28:33 | ERROR | stderr |     |     async for chunk in self.body_iterator:
2024-01-17 02:28:33 | ERROR | stderr |     |   File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 57, in iterate_in_threadpool
2024-01-17 02:28:33 | ERROR | stderr |     |     yield await anyio.to_thread.run_sync(_next, iterator)
2024-01-17 02:28:33 | ERROR | stderr |     |   File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
2024-01-17 02:28:33 | ERROR | stderr |     |     return await get_async_backend().run_sync_in_worker_thread(
2024-01-17 02:28:33 | ERROR | stderr |     |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
2024-01-17 02:28:33 | ERROR | stderr |     |     return await future
2024-01-17 02:28:33 | ERROR | stderr |     |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
2024-01-17 02:28:33 | ERROR | stderr |     |     result = context.run(func, *args)
2024-01-17 02:28:33 | ERROR | stderr |     |   File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 47, in _next
2024-01-17 02:28:33 | ERROR | stderr |     |     return next(iterator)
2024-01-17 02:28:33 | ERROR | stderr |     |   File "/app/LLaVA-Med/llava/serve/model_worker.py", line 292, in generate_stream_gate
2024-01-17 02:28:33 | ERROR | stderr |     |     for x in self.generate_stream(params):
2024-01-17 02:28:33 | ERROR | stderr |     |   File "/usr/local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
2024-01-17 02:28:33 | ERROR | stderr |     |     response = gen.send(None)
2024-01-17 02:28:33 | ERROR | stderr |     |   File "/app/LLaVA-Med/llava/serve/model_worker.py", line 260, in generate_stream
2024-01-17 02:28:33 | ERROR | stderr |     |     token = int(torch.multinomial(probs, num_samples=1))
2024-01-17 02:28:33 | ERROR | stderr |     | RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by NithinM29602** [comment]
I think the problem is in the weights itself. Better clone this weight https://huggingface.co/sbottazziunsam/LLaVA-Med_weights/tree/main and use these weights, check it out dude. It will work.

It's working for me....
![Screenshot 2024-03-10 121753](https://github.com/microsoft/LLaVA-Med/assets/92316309/15ecd0a6-3d47-4395-8a68-b420565929e5)

**Comment by dirtycomputer** [comment]
use https://huggingface.co/sbottazziunsam/LLaVA-Med_weights/tree/main still not working

**Comment by NithinM29602** [comment]
@dirtycomputer Use this notebook https://github.com/NithinM29602/Medi-Care/blob/main/swapna.ipynb and run it. I have modified few stuff out there like changing the old gradio version to the new one and there are some other files, Where I am working on my project. But if you just run the notebook you can play with the LLaVA-Med.

Have a Great Day...

**Comment by DonMuv** [comment]
@NithinM29602 How much GPU memory does this require?

**Comment by NithinM29602** [comment]
> @NithinM29602 How much GPU memory does this require?

It utilizes 16-20 GB pg GPU memory
