### ISSUE TITLE
RuntimeError: probability tensor contains either inf, nan or element < 0

### ISSUE THREAD

**Issue by yihp** [microsoft/LLaVA-Med#44]
Hello everyone,
My problem is when I run the inference example llava.eval.run_llava I get the error:
python -m llava.eval.run_llava
--model-name /app/LLaVA-Med/checkpoints/LLaVA-Med-7B
--image-file "/app/LLaVA-Med/llava/serve/examples/bio_patch.png"
--query "What is this image about?"
My original llama weights used Llama-2-7b-chat-hf
Running environment: cuda11.7, v100*4, torch 2.0.0+cu117, transformers, Python 3.10.0
**The error message is:**
root@976230b8c90c:/app/LLaVA-Med# bash scripts/chunyl/run_llava.sh
You are using the default legacy behavior of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. If you see this, DO NOT PANIC! This is expected, and simply means that the legacy (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set legacy=True. This should only be set if you understand what it means, and thouroughly read the reason why this was added as explained in huggingface/transformers#24565
Loading checkpoint shards: 100% | 2/2 [ 00:11<00:00, 5.58s/it]
/usr/local/lib/python3.10/site-packages/transformers/generation/utils.py:1411: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation )
warnings.warn(
Traceback (most recent call last):
File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/app/LLaVA-Med/llava/eval/run_llava.py", line 147, in
eval_model(args)
File "/app/LLaVA-Med/llava/eval/run_llava.py", line 103, in eval_model
output_ids = model.generate(
File "/usr/local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "/usr/local/lib/python3.10/site-packages/transformers/generation/utils.py", line 1642, in generate
return self.sample(
File "/usr/local/lib/python3.10/site-packages/transformers/generation/utils.py", line 2760, in sample
next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either inf, nan or element < 0
 **My attempts are as follows:**
1. Change LLaVA-Med-7B model config.json
tokenizer.pad_token = "[PAD]"
tokenizer.padding_side = "left"
2. Use bfloat16 precision, model = model.bfloat16()
3.changing the transformers version
But the problem has not been solved. 
Thank you in advance for any guidance or suggestions you can provide！

**Comment by M3Dade** [comment]
I retrain the model by editing the learning rate and batch sizes solving the problem

**Comment by yihp** [comment]
@M3Dade Thank you for your answer. I would like to ask if you have downloaded all the data sets?

**Comment by M3Dade** [comment]
@yihp yes

**Comment by yihp** [comment]
@M3Dade 感谢回复！请问可以加个好友吗？我想咨询一下相关问题

**Comment by yihp** [comment]
@M3Dade Can you download the complete training data set using the download script provided by the author?

**Comment by M3Dade** [comment]
@yihp  I download datasets from this  [repo](https://github.com/LLaVA-VL/LLaVA-Med-preview)

**Comment by yihp** [comment]
@M3Dade Thank you very much for your reply. i want to ask for that have you tested the training demo?

**Comment by dirtycomputer** [comment]
anyone solve this problem without retrain??

**Comment by adtserapio** [comment]
@dirtycomputer This error for me specifically was caused because I merged the delta using Llama-2-7b instead of llama-7b.
